spring:
  datasource:
    dynamic:
      p6spy: true
      druid: #以下是全局默认值，可以全局更改
        initial-size: 1
        max-active: 20
        min-idle: 1
        max-wait: 60000
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        validation-query: SELECT 'x'
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        filters: stat,wall
        web-stat-filter:
          enabled: true
          url-pattern: /*
          exclusions: "*.js , *.gif ,*.jpg ,*.png ,*.css ,*.ico , /druid/*"
          session-stat-max-count: 1000
          profile-enable: true
        stat-view-servlet:
          enabled: true
          url-pattern: /druid/*
          reset-enable: true
          login-username: admin
          login-password: admin
        wall:
          multi-statement-allow: true
      datasource:
        master:
          username:
          password:
          url: jdbc:p6spy:mysql://
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
          schema: db/schema.sql
          druid: #这里可以重写默认值
            initial-size: 5
            public-key:
        slave_1:
          username: sa
          password: "123456"
          url: jdbc:p6spy:mysql://
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
          druid:
            initial-size: 6
        slave_2:
          username: sa
          password: "123456"
          url: jdbc:p6spy:mysql://
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
        slave_3:
          username: sa
          password: "123456"
          url: jdbc:p6spy:mysql://
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure # 去除druid配置
  output:
    ansi:
      enabled: always

# mybatis-plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true  #是否开启自动驼峰命名规则（camel case）映射
    auto-mapping-unknown-column-behavior: warning
    cache-enabled: true
  global-config:
    banner: true
    db-config:
      # 逻辑删除  实体类字段上加上@TableLogic注解 使用mp自带方法删除和查找都会附带逻辑删除功能 (自己写的xml不会)
      logic-delete-field: flag #全局逻辑删除字段值
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  # 配置扫描通用枚举包 支持统配符 * 或者 ; 分割  ；使用 @EnumValue 注解枚举属性
  type-enums-package: com.code13.springbootdatasource.entity.enums
  # MyBatis Mapper 所对应的 XML 文件位置
  mapper-locations: classpath*:com/code13/**/dao/*.xml
  # MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名，注册后在 Mapper 对应的 XML 文件中可以直接使用类名，而不用使用全限定的类名(即 XML 中调用的时候不用包含包名)
  type-aliases-package: classpath*:com.code13.springbootdatasource.entity
  # 指定外部化 MyBatis Properties 配置，通过该配置可以抽离配置，实现不同环境的配置部署
  #configuration-properties:

logging:
  level:
    com.baomidou: debug
    org.springframework.jdbc.datasource.init: debug

