spring:
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: admin
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js , *.gif ,*.jpg ,*.png ,*.css ,*.ico , /druid/*"
        session-stat-max-count: 1000
        profile-enable: true
      db-type: mysql
    dynamic:
      primary: tjyun_uat
      p6spy: true
      druid: #以下是全局默认值，可以全局更改
        initial-size: 1
        max-active: 20
        min-idle: 1
        max-wait: 60000
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        validation-query: SELECT 'x'
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        filters: stat,wall
        wall:
          multi-statement-allow: true
      datasource:
        tjyun_uat:
          data-source-name: uat
          username: tjyk
          password: tjyk!2019
          url: jdbc:mysql://rm-bp11bdf19z4m594yrjo.mysql.rds.aliyuncs.com:3306/tjyun_test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
          #          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
          driver-class-name: com.mysql.cj.jdbc.Driver
          #          schema: db/schema.sql
          druid: #这里可以重写默认值
            #            db-type: mysql
            initial-size: 5
        tjyun_dev:
          data-source-name: dev
          username: root
          password: soofuju123
          url: jdbc:mysql://117.89.135.182:3306/tjyun?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
          driver-class-name: com.mysql.cj.jdbc.Driver
          druid:
            #            db-type: mysql
            initial-size: 6
        tjyun_local:
          data-source-name: local
          username: code13
          password: 1024
          url: jdbc:mysql://127.0.0.1:3306/tjyun?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
          driver-class-name: com.mysql.cj.jdbc.Driver
        # 可以配置多个从库 每一个均可以单独配置 druid
  #        slave_3:
  #          username: sa
  #          password: "123456"
  #          url: jdbc:p6spy:mysql://
  #          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure # 去除druid自动配置配置重要！！！
  output:
    ansi:
      enabled: always

# mybatis-plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true  #是否开启自动驼峰命名规则（camel case）映射
    auto-mapping-unknown-column-behavior: warning
    cache-enabled: true
  global-config:
    banner: true
    db-config:
      # 逻辑删除  实体类字段上加上@TableLogic注解 使用mp自带方法删除和查找都会附带逻辑删除功能 (自己写的xml不会)
      logic-delete-field: flag #全局逻辑删除字段值
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  # 配置扫描通用枚举包 支持统配符 * 或者 ; 分割  ；使用 @EnumValue 注解枚举属性
  type-enums-package: com.code13.springbootdatasource.entity.enums
  # MyBatis Mapper 所对应的 XML 文件位置
  mapper-locations: classpath*:com/code13/**/dao/*.xml
  # MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名，注册后在 Mapper 对应的 XML 文件中可以直接使用类名，而不用使用全限定的类名(即 XML 中调用的时候不用包含包名)
  type-aliases-package: classpath*:com.code13.springbootdatasource.entity
  # 指定外部化 MyBatis Properties 配置，通过该配置可以抽离配置，实现不同环境的配置部署
  #configuration-properties:

logging:
  level:
    com.baomidou: debug
    org.springframework.jdbc.datasource.init: debug

